spring:
  application:
    name: service-user-center
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.99.195.142:3306/broker?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: abcd1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 47.99.195.142
    port: 6379
    password: abcd1234

ribbon:
  eureka:
    enabled: true

server:
  port: 8081

eureka:
  instance:
    hostName: localhost
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 30
  client:
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wx.dao

mapper:
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.* : debug