spring:
  application:
    name: service-zuul

server:
  port: 8090

eureka:
  instance:
    hostName: localhost
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 30
  client:
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

zuul:
  routes:
    usercenter:
      path: /usercenter/**
      serviceId: service-user-center

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
