server:
  port: 8010

spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/quanquan012/configuration/
          search-paths: service-user-center,service-zuul,service-eureka
      label: master

eureka:
  instance:
    hostName: localhost
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 30
  client:
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/