spring:
  application:
    name: service-eureka
server:
  port: 8080

eureka:
  instance:
    ip-address: 47.110.73.43
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka/
  server:
    enable-self-preservation: false